LEFT_CAN_INTERFACE=can-left
RIGHT_CAN_INTERFACE=can-right
LEFT_CAN_SERIAL=015213EF68D8345BBAA6D57818A4EC3A
RIGHT_CAN_SERIAL=AEEDE4FD23DEA4AFCA6B3EAA55ABC28A
CAN_BITRATE=1000000
CAN_DBITRATE=5000000
CAN_SAMPLE_POINT=0.80
CAN_DSAMPLE_POINT=0.875
CAN_RESTART_MS=100
