from importlib import import_module

from .abi import (
    abi_capabilities,
    abi_version,
    articore_runtime_abi_version,
    articore_runtime_capabilities,
    articore_runtime_library_path,
)
from .core import (
    Controller,
    ControllerGroup,
    Motor,
    PreparedMitBatch,
    PreparedPosVelBatch,
)
from .runtime import ArticoreRuntime
from .robot_model import (
    IkOptions,
    IkResult,
    JacobianReference,
    NativeRobotModel,
    RobotModelInfo,
    RobotPose,
    RobotSide,
)
from .runtime_models import (
    ActiveCapability,
    CommandLifetime,
    ConnectChannelResult,
    ConnectErrorCode,
    ConnectMotorResult,
    ConnectReport,
    DisableMotorResult,
    DisableReport,
    EnableMotorResult,
    EnableReport,
    GripperCommand,
    GripperControlState,
    GripperFaultAction,
    GripperHealth,
    GripperProductBinding,
    GravityCompensationPhase,
    GravityCompensationStatus,
    GravityProductBinding,
    JointControlConfig,
    JointPositionTarget,
    JointSafetyLimits,
    MitTorqueLimitJointStats,
    MitTorqueLimitStats,
    RuntimeConfig,
    RuntimeControlMode,
    RuntimeMitCommand,
    RuntimeMotor,
    RuntimePvCommand,
    RuntimeTransportHealth,
    SafetyHealth,
    SafetyState,
)
from .dm_device_runtime import ensure_dm_device_runtime
from .errors import (
    AbiLoadError,
    CallError,
    FeedbackMotorFaultError,
    FeedbackRequestError,
    FeedbackTimeoutError,
    FeedbackTransportError,
    IncompleteFeedbackError,
    MotorBridgeError,
    RuntimeCallError,
    RuntimeTransactionError,
)
from .models import (
    FeedbackStats,
    FeedbackIntegrityStats,
    FeedbackRejectionReason,
    FeedbackReport,
    MitCommand,
    Mode,
    MotorErrorCode,
    MotorCandidate,
    MotorDiscoveryResult,
    MotorState,
    PosVelCommand,
    PresencePolicy,
    PresenceState,
    TransportCapabilities,
    TransportHealth,
)
from ._version import VERSION


_REGISTER_EXPORTS = {
    "RegisterSpec",
    "DAMIAO_RW_REGISTERS",
    "DAMIAO_HIGH_IMPACT_RIDS",
    "DAMIAO_PROTECTION_RIDS",
    "get_damiao_register_spec",
    "RID_CTRL_MODE",
    "RID_MST_ID",
    "RID_ESC_ID",
    "RID_TIMEOUT",
    "RID_PMAX",
    "RID_VMAX",
    "RID_TMAX",
    "RID_KP_ASR",
    "RID_KI_ASR",
    "RID_KP_APR",
    "RID_KI_APR",
    "MODE_MIT",
    "MODE_POS_VEL",
    "MODE_VEL",
    "MODE_FORCE_POS",
}


def __getattr__(name: str):
    if name in _REGISTER_EXPORTS:
        module = import_module(".damiao_registers", __name__)
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | _REGISTER_EXPORTS)


def get_version() -> str:
    return VERSION


__version__ = get_version()

__all__ = [
    "__version__",
    "get_version",
    "abi_version",
    "abi_capabilities",
    "articore_runtime_library_path",
    "articore_runtime_abi_version",
    "articore_runtime_capabilities",
    "ensure_dm_device_runtime",
    "Controller",
    "ControllerGroup",
    "PreparedMitBatch",
    "PreparedPosVelBatch",
    "Motor",
    "ArticoreRuntime",
    "NativeRobotModel",
    "RobotSide",
    "JacobianReference",
    "RobotModelInfo",
    "RobotPose",
    "IkOptions",
    "IkResult",
    "RuntimeConfig",
    "RuntimeMotor",
    "RuntimeControlMode",
    "CommandLifetime",
    "ConnectErrorCode",
    "ConnectChannelResult",
    "ConnectMotorResult",
    "ConnectReport",
    "SafetyState",
    "ActiveCapability",
    "JointControlConfig",
    "JointPositionTarget",
    "JointSafetyLimits",
    "MitTorqueLimitJointStats",
    "MitTorqueLimitStats",
    "GripperProductBinding",
    "GravityProductBinding",
    "GravityCompensationPhase",
    "GravityCompensationStatus",
    "GripperCommand",
    "RuntimeMitCommand",
    "RuntimePvCommand",
    "EnableMotorResult",
    "EnableReport",
    "DisableMotorResult",
    "DisableReport",
    "RuntimeTransportHealth",
    "GripperControlState",
    "GripperFaultAction",
    "GripperHealth",
    "SafetyHealth",
    "Mode",
    "PresencePolicy",
    "PresenceState",
    "MotorCandidate",
    "MotorDiscoveryResult",
    "MotorState",
    "FeedbackStats",
    "FeedbackIntegrityStats",
    "FeedbackRejectionReason",
    "FeedbackReport",
    "MotorErrorCode",
    "MitCommand",
    "PosVelCommand",
    "TransportCapabilities",
    "TransportHealth",
    "RegisterSpec",
    "DAMIAO_RW_REGISTERS",
    "DAMIAO_HIGH_IMPACT_RIDS",
    "DAMIAO_PROTECTION_RIDS",
    "get_damiao_register_spec",
    "RID_CTRL_MODE",
    "RID_MST_ID",
    "RID_ESC_ID",
    "RID_TIMEOUT",
    "RID_PMAX",
    "RID_VMAX",
    "RID_TMAX",
    "RID_KP_ASR",
    "RID_KI_ASR",
    "RID_KP_APR",
    "RID_KI_APR",
    "MODE_MIT",
    "MODE_POS_VEL",
    "MODE_VEL",
    "MODE_FORCE_POS",
    "MotorBridgeError",
    "AbiLoadError",
    "CallError",
    "RuntimeCallError",
    "RuntimeTransactionError",
    "FeedbackRequestError",
    "FeedbackTimeoutError",
    "IncompleteFeedbackError",
    "FeedbackTransportError",
    "FeedbackMotorFaultError",
]
