import ctypes
from typing import Any

class CState(ctypes.Structure): ...
class CFeedbackStats(ctypes.Structure): ...
class CFeedbackReport(ctypes.Structure): ...
class CDiscoveryCandidate(ctypes.Structure): ...
class CDiscoveryResult(ctypes.Structure): ...
class CTransportCapabilities(ctypes.Structure): ...
class CTransportCapabilitiesV2(ctypes.Structure): ...
class CRegisterInfo(ctypes.Structure): ...
class CMitBatchCommand(ctypes.Structure): ...
class CPosVelBatchCommand(ctypes.Structure): ...

class Abi:
    lib: ctypes.CDLL
    has_dm_device_ex: bool
    has_controller_group: bool
    has_transport_capabilities: bool
    has_transport_capabilities_v2: bool
    has_socketcanfd_ex: bool
    has_transport_health: bool
    has_motor_presence_discovery: bool
    has_structured_feedback_report: bool
    def __init__(self) -> None: ...

def get_abi() -> Abi: ...
def abi_version() -> str: ...
def abi_capabilities() -> dict[str, Any]: ...
def articore_runtime_library_path() -> str: ...
def articore_runtime_abi_version() -> str: ...
def articore_runtime_capabilities() -> dict[str, bool]: ...
def damiao_register_info(rid: int) -> tuple[str, str] | None: ...

MOTOR_OK: int
MOTOR_ERROR_INVALID_ARGUMENT: int
MOTOR_ERROR_TRANSPORT: int
MOTOR_ERROR_FEEDBACK_TIMEOUT: int
MOTOR_ERROR_FEEDBACK_INCOMPLETE: int
MOTOR_ERROR_MOTOR_FAULT: int
