import ctypes
from typing import Any

class CState(ctypes.Structure): ...
class CFeedbackStats(ctypes.Structure): ...
class CTransportCapabilities(ctypes.Structure): ...
class CRegisterInfo(ctypes.Structure): ...
class CMitBatchCommand(ctypes.Structure): ...
class CPosVelBatchCommand(ctypes.Structure): ...

class Abi:
    lib: ctypes.CDLL
    has_dm_device_ex: bool
    has_controller_group: bool
    has_transport_capabilities: bool
    def __init__(self) -> None: ...

def get_abi() -> Abi: ...
def abi_version() -> str: ...
def abi_capabilities() -> dict[str, Any]: ...
def damiao_register_info(rid: int) -> tuple[str, str] | None: ...
