import ctypes
from typing import Any

class CState(ctypes.Structure): ...
class CFeedbackStats(ctypes.Structure): ...
class CRegisterInfo(ctypes.Structure): ...

class Abi:
    lib: ctypes.CDLL
    def __init__(self) -> None: ...

def get_abi() -> Abi: ...
def abi_version() -> str: ...
def abi_capabilities() -> dict[str, Any]: ...
def damiao_register_info(rid: int) -> tuple[str, str] | None: ...
