from collections.abc import Sequence
from types import TracebackType

from .models import (
    FeedbackStats,
    FeedbackIntegrityStats,
    MitCommand,
    Mode,
    MotorCandidate,
    MotorDiscoveryResult,
    MotorState,
    PosVelCommand,
    TransportCapabilities,
    TransportHealth,
)

class Controller:
    def __init__(self, channel: str = "can0") -> None: ...
    @classmethod
    def from_socketcanfd(
        cls, channel: str = "can0", enable_brs: bool = True
    ) -> Controller: ...
    @classmethod
    def from_dm_serial(
        cls, serial_port: str = "/dev/ttyACM0", baud: int = 1_000_000
    ) -> Controller: ...
    @classmethod
    def from_dm_device(
        cls,
        dm_device_type: str = "usb2canfd-dual",
        dm_channel: str | int = "0",
        bitrate: int = 1_000_000,
        data_bitrate: int = 5_000_000,
        *,
        device: str | None = None,
        channel: str | int | None = None,
    ) -> Controller: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def shutdown(self) -> None: ...
    def close_bus(self) -> None: ...
    def enable_all(self) -> None: ...
    def disable_all(self) -> None: ...
    def poll_feedback_once(self) -> None: ...
    def request_feedback_all(self, timeout_ms: int = 50) -> None: ...
    def set_tx_gap_us(self, gap_us: int) -> None: ...
    def transport_capabilities(self) -> TransportCapabilities: ...
    def transport_health(self) -> TransportHealth: ...
    def add_damiao_motor(self, motor_id: int, feedback_id: int, model: str) -> Motor: ...
    def discover_damiao_motors(
        self,
        candidates: Sequence[MotorCandidate],
        timeout_ms: int = 50,
        retries: int = 1,
    ) -> tuple[MotorDiscoveryResult, ...]: ...
    def __enter__(self) -> Controller: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

class Motor:
    def __init__(self, ptr: int, controller: Controller | None = None) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def clear_error(self) -> None: ...
    def set_zero_position(self) -> None: ...
    def ensure_mode(self, mode: Mode | int, timeout_ms: int = 1000) -> None: ...
    def send_mit(
        self, pos: float, vel: float, kp: float, kd: float, tau: float
    ) -> None: ...
    def send_pos_vel(self, pos: float, vlim: float) -> None: ...
    def send_vel(self, vel: float) -> None: ...
    def send_force_pos(self, pos: float, vlim: float, ratio: float) -> None: ...
    def request_feedback(self) -> None: ...
    def request_fresh_state(self, timeout_ms: int = 50) -> MotorState: ...
    def set_can_timeout_ms(self, timeout_ms: int) -> None: ...
    def store_parameters(self) -> None: ...
    def write_register_f32(self, rid: int, value: float) -> None: ...
    def write_register_u32(self, rid: int, value: int) -> None: ...
    def get_register_f32(self, rid: int, timeout_ms: int = 1000) -> float: ...
    def get_register_u32(self, rid: int, timeout_ms: int = 1000) -> int: ...
    def damiao_get_param_f32(self, param_id: int, timeout_ms: int = 1000) -> float: ...
    def damiao_get_param_u32(self, param_id: int, timeout_ms: int = 1000) -> int: ...
    def damiao_write_param_f32(self, param_id: int, value: float) -> None: ...
    def damiao_write_param_u32(self, param_id: int, value: int) -> None: ...
    def get_state(self) -> MotorState | None: ...
    def get_feedback_stats(self) -> FeedbackStats: ...
    def get_feedback_integrity_stats(self) -> FeedbackIntegrityStats: ...
    def __enter__(self) -> Motor: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

class ControllerGroup:
    def __init__(self, controllers: Sequence[Controller]) -> None: ...
    def __del__(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def send_mit(self, commands: Sequence[MitCommand]) -> None: ...
    def send_pos_vel(self, commands: Sequence[PosVelCommand]) -> None: ...
    def prepare_mit(self, motors: Sequence[Motor]) -> PreparedMitBatch: ...
    def prepare_pos_vel(self, motors: Sequence[Motor]) -> PreparedPosVelBatch: ...
    def __enter__(self) -> ControllerGroup: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

class PreparedPosVelBatch:
    def __init__(self, group: ControllerGroup, motors: Sequence[Motor]) -> None: ...
    @property
    def motor_count(self) -> int: ...
    def send(
        self,
        positions: Sequence[float],
        velocity_limits: float | Sequence[float],
    ) -> None: ...

class PreparedMitBatch:
    def __init__(self, group: ControllerGroup, motors: Sequence[Motor]) -> None: ...
    @property
    def motor_count(self) -> int: ...
    def send(
        self,
        positions: Sequence[float],
        velocities: float | Sequence[float],
        stiffness: float | Sequence[float],
        damping: float | Sequence[float],
        feedforward_torques: float | Sequence[float],
    ) -> None: ...
