from types import TracebackType

from .models import FeedbackStats, Mode, MotorState

class Controller:
    def __init__(self, channel: str = "can0") -> None: ...
    @classmethod
    def from_socketcanfd(cls, channel: str = "can0") -> Controller: ...
    @classmethod
    def from_dm_serial(
        cls, serial_port: str = "/dev/ttyACM0", baud: int = 1_000_000
    ) -> Controller: ...
    @classmethod
    def from_dm_device(
        cls, dm_device_type: str = "usb2canfd-dual", dm_channel: str = "0"
    ) -> Controller: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def shutdown(self) -> None: ...
    def close_bus(self) -> None: ...
    def enable_all(self) -> None: ...
    def disable_all(self) -> None: ...
    def poll_feedback_once(self) -> None: ...
    def request_feedback_all(self, timeout_ms: int = 50) -> None: ...
    def set_tx_gap_us(self, gap_us: int) -> None: ...
    def add_damiao_motor(self, motor_id: int, feedback_id: int, model: str) -> Motor: ...
    def __enter__(self) -> Controller: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

class Motor:
    def __init__(self, ptr: int, controller: Controller | None = None) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def clear_error(self) -> None: ...
    def set_zero_position(self) -> None: ...
    def ensure_mode(self, mode: Mode | int, timeout_ms: int = 1000) -> None: ...
    def send_mit(
        self, pos: float, vel: float, kp: float, kd: float, tau: float
    ) -> None: ...
    def send_pos_vel(self, pos: float, vlim: float) -> None: ...
    def send_vel(self, vel: float) -> None: ...
    def send_force_pos(self, pos: float, vlim: float, ratio: float) -> None: ...
    def request_feedback(self) -> None: ...
    def request_fresh_state(self, timeout_ms: int = 50) -> MotorState: ...
    def set_can_timeout_ms(self, timeout_ms: int) -> None: ...
    def store_parameters(self) -> None: ...
    def write_register_f32(self, rid: int, value: float) -> None: ...
    def write_register_u32(self, rid: int, value: int) -> None: ...
    def get_register_f32(self, rid: int, timeout_ms: int = 1000) -> float: ...
    def get_register_u32(self, rid: int, timeout_ms: int = 1000) -> int: ...
    def damiao_get_param_f32(self, param_id: int, timeout_ms: int = 1000) -> float: ...
    def damiao_get_param_u32(self, param_id: int, timeout_ms: int = 1000) -> int: ...
    def damiao_write_param_f32(self, param_id: int, value: float) -> None: ...
    def damiao_write_param_u32(self, param_id: int, value: int) -> None: ...
    def get_state(self) -> MotorState | None: ...
    def get_feedback_stats(self) -> FeedbackStats: ...
    def __enter__(self) -> Motor: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
