from .models import FeedbackReport, MotorErrorCode
from .runtime_models import ConnectReport, DisableReport, EnableReport

class MotorBridgeError(RuntimeError): ...
class AbiLoadError(MotorBridgeError): ...
class CallError(MotorBridgeError): ...
class RuntimeCallError(CallError): ...
class RuntimeTransactionError(RuntimeCallError):
    report: ConnectReport | EnableReport | DisableReport
    def __init__(self, message: str, report: ConnectReport | EnableReport | DisableReport) -> None: ...
class FeedbackRequestError(CallError):
    report: FeedbackReport
    error_code: MotorErrorCode
    missing_motor_ids: tuple[int, ...]
    missing_count: int
    timeout_ms: int
    expected_count: int
    received_count: int
    def __init__(self, message: str, report: FeedbackReport) -> None: ...
class FeedbackTimeoutError(FeedbackRequestError): ...
class IncompleteFeedbackError(FeedbackRequestError): ...
class FeedbackTransportError(FeedbackRequestError): ...
class FeedbackMotorFaultError(FeedbackRequestError): ...
