from .models import FeedbackReport, MotorErrorCode

class MotorBridgeError(RuntimeError): ...
class AbiLoadError(MotorBridgeError): ...
class CallError(MotorBridgeError): ...
class FeedbackRequestError(CallError):
    report: FeedbackReport
    error_code: MotorErrorCode
    missing_motor_ids: tuple[int, ...]
    missing_count: int
    timeout_ms: int
    expected_count: int
    received_count: int
    def __init__(self, message: str, report: FeedbackReport) -> None: ...
class FeedbackTimeoutError(FeedbackRequestError): ...
class IncompleteFeedbackError(FeedbackRequestError): ...
class FeedbackTransportError(FeedbackRequestError): ...
class FeedbackMotorFaultError(FeedbackRequestError): ...
