from dataclasses import dataclass
from enum import IntEnum
from types import TracebackType
from typing import Sequence

class RobotSide(IntEnum):
    LEFT: RobotSide
    RIGHT: RobotSide

class JacobianReference(IntEnum):
    LOCAL: JacobianReference
    WORLD: JacobianReference
    LOCAL_WORLD_ALIGNED: JacobianReference

@dataclass(frozen=True)
class RobotModelInfo:
    product_id: str
    side: RobotSide
    dof: int
    joint_names: tuple[str, ...]
    end_effector_frame: str
    lower_limits: tuple[float, ...]
    upper_limits: tuple[float, ...]

@dataclass(frozen=True)
class RobotPose:
    position: tuple[float, float, float]
    rotation: tuple[tuple[float, float, float], ...]
    homogeneous: tuple[tuple[float, float, float, float], ...]

@dataclass(frozen=True)
class IkOptions:
    max_iterations: int = ...
    max_retries: int = ...
    tolerance: float = ...
    step_size: float = ...
    damping: float = ...
    random_seed: int = ...

@dataclass(frozen=True)
class IkResult:
    q: tuple[float, ...]
    success: bool
    error: float
    iterations: int

class NativeRobotModel:
    def __init__(self, product_id: str = ..., side: RobotSide | int = ...) -> None: ...
    @property
    def info(self) -> RobotModelInfo: ...
    def fk(self, q: Sequence[float]) -> RobotPose: ...
    def jacobian(self, q: Sequence[float], reference: JacobianReference | int = ...) -> tuple[tuple[float, ...], ...]: ...
    def gravity(self, q: Sequence[float]) -> tuple[float, ...]: ...
    def mass_matrix(self, q: Sequence[float]) -> tuple[tuple[float, ...], ...]: ...
    def coriolis_matrix(self, q: Sequence[float], dq: Sequence[float]) -> tuple[tuple[float, ...], ...]: ...
    def nonlinear_effects(self, q: Sequence[float], dq: Sequence[float]) -> tuple[float, ...]: ...
    def rnea(self, q: Sequence[float], dq: Sequence[float], ddq: Sequence[float]) -> tuple[float, ...]: ...
    def aba(self, q: Sequence[float], dq: Sequence[float], torque: Sequence[float]) -> tuple[float, ...]: ...
    def ik(self, target: RobotPose, initial_q: Sequence[float], options: IkOptions = ...) -> IkResult: ...
    def close(self) -> None: ...
    def __enter__(self) -> NativeRobotModel: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
