from collections.abc import Sequence
from .core import Controller, ControllerGroup, Motor
from .models import PresenceState
from .runtime_models import *

class ArticoreRuntime:
    def __init__(self, config: RuntimeConfig, controller_group: ControllerGroup, left_controller: Controller | None, right_controller: Controller | None, motors: Sequence[RuntimeMotor]) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def control_hz(self) -> int: ...
    @property
    def mit_torque_limit_stats(self) -> MitTorqueLimitStats: ...
    def configure_joints(self, configs: Sequence[JointControlConfig]) -> None: ...
    def configure_joint_safety_limits(self, limits: Sequence[JointSafetyLimits]) -> None: ...
    def configure_gripper_products(self, bindings: Sequence[GripperProductBinding]) -> None: ...
    def configure_gravity_products(self, bindings: Sequence[GravityProductBinding]) -> None: ...
    def declare_motor_presence(self, role: str, state: PresenceState) -> None: ...
    def motor_presence(self, role: str) -> PresenceState: ...
    @property
    def active_capabilities(self) -> ActiveCapability: ...
    def connect(self) -> ConnectReport: ...
    def last_connect_report(self) -> ConnectReport: ...
    def enable(self, mode: RuntimeControlMode) -> EnableReport: ...
    def last_enable_report(self) -> EnableReport: ...
    def start_gravity_compensation(self, transition_ms: int = ...) -> None: ...
    def stop_gravity_compensation(self) -> None: ...
    @property
    def gravity_compensation_status(self) -> GravityCompensationStatus: ...
    def set_joint_mit(self, targets: Sequence[JointPositionTarget], velocity: float) -> None: ...
    def set_joint_pv(self, targets: Sequence[JointPositionTarget], velocity: float) -> None: ...
    def submit_mit(self, commands: Sequence[RuntimeMitCommand], lifetime: CommandLifetime = ...) -> None: ...
    def submit_pv(self, commands: Sequence[RuntimePvCommand], lifetime: CommandLifetime = ...) -> None: ...
    def set_grippers(self, commands: Sequence[GripperCommand]) -> None: ...
    def report_feedback_failure(self, side: int, reason: str) -> None: ...
    def disable(self) -> DisableReport: ...
    def last_disable_report(self) -> DisableReport: ...
    def estop(self, reason: str) -> None: ...
    def recover(self) -> None: ...
    @property
    def health(self) -> SafetyHealth: ...
    def close(self) -> None: ...
    def __enter__(self) -> ArticoreRuntime: ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
